Repository planetarium/libplanet-explorer-frontend, pull requests merged in 2019-08, with the labels that each got.

#7 Update GraphQL schema
  src/api.graphql
  src/schema.graphql
Labels: enhancement

#8 Update GraphQL schema
  src/schema.graphql
Labels: enhancement

#11 More detailed introduction in README
  README.md
Labels: documentation

#12 Navigate to block page by its hash
  src/components/Layout.tsx
Labels: enhancement

#13 Block previous hash and difficulty
  src/pages/block.tsx
Labels: enhancement

#16 Add transaction list to block page
  src/api.graphql
  src/pages/block.tsx
Labels: good first issue

#19 Recent blocks summary
  .editorconfig
  src/pages/index.tsx
Labels: enhancement, good first issue

#21 Fix rendering issue
  src/misc/useQueryString.ts
Labels: bug

#24 Add transaction page
  package-lock.json
  src/api.graphql
  src/pages/block.tsx
  src/pages/transaction.tsx
  src/schema.graphql
Labels: good first issue

#23 Tx # in block list
  src/api.graphql
  src/pages/index.tsx
Labels: good first issue

#29 Make an option to list only blocks having any tx
  package-lock.json
  src/api.graphql
  src/pages/index.tsx
  src/schema.graphql
Labels: enhancement
